### ISSUE TITLE
examples do not work

### ISSUE THREAD

**Issue by Berhinj** [Open-ET/openet-ptjpl#1]
Super valuable github repo, I wish it worked but the examples don't work.

```
import openet.ptjpl as ptjpl

landsat_img = ee.Image('LANDSAT/LC08/C02/T1_L2/LC08_044033_20170716')
et_actual = ptjpl.Image.from_landsat_c2_sr(landsat_img).et
et_actual.getInfo()
```

It gets me 

`EEException: Image.load: Image asset 'projects/openet/ptjpl/ancillary/fAPARmax' not found.`

Anybody managed to make it run?

**Comment by cgmorton** [comment]
I think the issue is that asset was not public.  Will you try it again in a little bit?  I'm checking the other ancillary assets to make sure they are all public.

**Comment by Berhinj** [comment]
Yes I can re-try tomorrow. Did you manage to make the ancillary dataset public ?

**Comment by cgmorton** [comment]
Yes
